
import re

existing_file_path = r"c:\Users\Wendell Richins\OneDrive\Desktop\games\Crypto-puzzles-main\Crypto-puzzles-main\src\data\customQuotes.js"

with open(existing_file_path, "r", encoding='utf-8') as f:
    content = f.read()

# Extract existing quotes
existing_quotes = set()
matches = re.findall(r'quote:\s*"(.*?)",', content)
for m in matches:
    existing_quotes.add(m)

print(f"Found {len(existing_quotes)} existing quotes.")

candidates = [
    ("The inner machinations of my mind are an enigma.", "Patrick Star"),
    ("We don't make mistakes, just happy little accidents.", "Bob Ross"),
    ("The way I see it, if you want the rainbow, you gotta put up with the rain.", "Dolly Parton"),
    ("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"),
    ("It does not do to dwell on dreams and forget to live.", "Albus Dumbledore"),
    ("Remember, with great power comes great responsibility.", "Uncle Ben"),
    ("You're gonna need a bigger boat.", "Martin Brody (Jaws)"), # 32 chars - check len
    ("They may take our lives, but they'll never take our freedom!", "William Wallace"),
    ("Life is what happens when you're busy making other plans.", "John Lennon"),
    ("Get your stinking paws off me, you damned dirty ape!", "George Taylor"),
    ("A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.", "Hannibal Lecter"),
    ("You don't have to burn books to destroy a culture. Just get people to stop reading them.", "Ray Bradbury"),
    ("There is some good in this world, and it's worth fighting for.", "Samwise Gamgee"),
    ("I would rather share one lifetime with you than face all the ages of this world alone.", "Arwen"),
    ("Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", "Neil Gaiman"),
    ("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
    ("You define your own life. Don't let other people write your script.", "Oprah Winfrey"),
    ("Look up at the stars and not down at your feet. Try to make sense of what you see.", "Stephen Hawking"),
    ("However difficult life may seem, there is always something you can do and succeed at.", "Stephen Hawking"),
    ("To handle yourself, use your head; to handle others, use your heart.", "Eleanor Roosevelt"),
    ("If you can't fly then run, if you can't run then walk, if you can't walk then crawl.", "Martin Luther King Jr."),
    ("We must accept finite disappointment, but never lose infinite hope.", "Martin Luther King Jr."),
    ("Injustice anywhere is a threat to justice everywhere.", "Martin Luther King Jr."),
    ("The glory of living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    ("Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"),
    ("Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "Albert Einstein"),
    ("Insanity is doing the same thing over and over again and expecting different results.", "Albert Einstein"),
    ("The person who never made a mistake never tried anything new.", "Albert Einstein"),
    ("We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde"),
    ("To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson"),
    ("It is better to be hated for what you are than to be loved for what you are not.", "Andre Gide"),
    ("Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", "Marilyn Monroe"),
    ("Good friends, good books, and a sleepy conscience: this is the ideal life.", "Mark Twain"),
    ("I haven't spoken to my wife in years. I didn't want to interrupt her.", "Rodney Dangerfield"),
    ("I used to sell furniture for a living. The trouble was, it was my own.", "Les Dawson"),
    ("I want my children to have all the things I couldn't afford. Then I want to move in with them.", "Phyllis Diller"),
    ("My fake plants died because I did not pretend to water them.", "Mitch Hedberg"),
    ("I’m sick of following my dreams, man. I’m just going to ask where they’re going and hook up with them later.", "Mitch Hedberg"),
    ("Whatever you do, always give 100%. Unless you’re donating blood.", "Bill Murray"),
    ("Don't sweat the petty things and don't pet the sweaty things.", "George Carlin"),
    ("I’m sorry, if you were right, I’d agree with you.", "Robin Williams"),
    ("Laziness is nothing more than the habit of resting before you get tired.", "Jules Renard"),
    ("Doing nothing is very hard to do. You never know when you're finished.", "Leslie Nielsen"),
    ("If you think nobody cares if you're alive, try missing a couple of car payments.", "Flip Wilson"),
    ("The road to success is dotted with many tempting parking spaces.", "Will Rogers"),
    ("Everyone has a plan until they get punched in the mouth.", "Mike Tyson"),
    ("Before you marry a person, you should first make them use a computer with slow Internet to see who they really are.", "Will Ferrell"),
    ("I walk around like everything’s fine, but deep down, inside my shoe, my sock is sliding off.", "Anonymous"),
    ("Common sense is like deodorant. The people who need it most never use it.", "Bill Murray"),
    ("I’m not arguing, I’m just explaining why I’m right.", "Anonymous"),
    ("If at first you don't succeed, then skydiving isn't for you.", "Steven Wright"),
    ("Don't let your ears hear what your eyes didn't see.", "Trevor Noah"),
    ("Everything I have I owe to this job... this stupid, wonderful, boring, amazing job.", "Jim Halpert"),
    ("Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.", "Michael Scott"),
    ("I am fast. To give you a reference point I am somewhere between a snake and a mongoose... And a panther.", "Dwight Schrute"),
    ("Sometimes I'll start a sentence and I don't even know where it's going. I just hope I find it along the way.", "Michael Scott"),
    ("If you can't love yourself, how in the hell you gonna love somebody else?", "RuPaul"),
    ("What if I told you that everything you know is a lie?", "Morpheus"),
    ("I don't think that word means what you think it means.", "Inigo Montoya"),
    ("Life is pain, Highness. Anyone who says differently is selling something.", "Westley"),
    ("You either die a hero, or you live long enough to see yourself become the villain.", "Harvey Dent"),
    ("Why do we fall, sir? So that we can learn to pick ourselves up.", "Alfred Pennyworth"),
    ("Nobody exists on purpose. Nobody belongs anywhere. Everybody's gonna die. Come watch TV.", "Morty Smith"),
    ("Listen, I'm not the nicest guy in the universe because I'm the smartest.", "Rick Sanchez"),
    ("To live is to risk it all; otherwise you're just an inert chunk of molecules drifting wherever the universe blows you.", "Rick Sanchez"),
    ("The only way out of the labyrinth of suffering is to forgive.", "John Green"),
    ("We've all got both light and dark inside us. What matters is the part we choose to act on.", "Sirius Black"),
    ("Words are, in my not-so-humble opinion, our most inexhaustible source of magic.", "Albus Dumbledore"),
    ("It is our choices, Harry, that show what we truly are, far more than our abilities.", "Albus Dumbledore"),
    ("Whatever our souls are made of, his and mine are the same.", "Emily Brontë"),
    ("I am no bird; and no net ensnares me: I am a free human being with an independent will.", "Charlotte Brontë"),
    ("The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", "John Milton"),
    ("Beware; for I am fearless, and therefore powerful.", "Mary Shelley"),
    ("There are years that ask questions and years that answer.", "Zora Neale Hurston"),
    ("Memories warm you up from the inside. But they also tear you apart.", "Haruki Murakami"),
    ("If you only read the books that everyone else is reading, you can only think what everyone else is thinking.", "Haruki Murakami"),
    ("If it's broken, fix it. If you can't fix it, break it some more.", "Unknown"),
    ("Always borrow money from a pessimist. They won't expect it back.", "Oscar Wilde"),
    ("The best bridge between despair and hope is a good night’s sleep.", "E. Joseph Cossman"),
    ("Drink some water, you beautiful and capable but dehydrated land mermaid.", "Ann Perkins"),
    ("Don’t let anyone treat you like free salsa. You are guacamole, baby. You are guacamole.", "Unknown"),
    ("Your secrets are safe with me. I wasn't even listening.", "Unknown"),
    ("I finally realized that people are prisoners of their phones... that's why it's called a cell phone.", "Unknown"),
    ("Do not go gentle into that good night. Rage, rage against the dying of the light.", "Dylan Thomas"),
    ("Even the darkest night will end and the sun will rise.", "Victor Hugo"),
    ("You are the master of your destiny. You can influence, direct and control your own environment.", "Napoleon Hill"),
    ("Three things cannot be long hidden: the sun, the moon, and the truth.", "Buddha"),
    ("You only live once, but if you do it right, once is enough.", "Mae West"),
    ("Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "Maya Angelou"),
    ("If you tell the truth, you don't have to remember anything.", "Mark Twain"),
    ("I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin.", "Martin Luther King Jr."),
    ("We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets.", "Winston Churchill"),
    ("Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty.", "Abraham Lincoln"),
    ("Who controls the past controls the future. Who controls the present controls the past.", "George Orwell"),
    ("War is peace. Freedom is slavery. Ignorance is strength.", "George Orwell"),
    ("Whatever is done for love always occurs beyond good and evil.", "Friedrich Nietzsche"),
    ("He who has a why to live for can bear almost any how.", "Friedrich Nietzsche"),
    ("I like long walks, especially when they are taken by people who annoy me.", "Fred Allen"),
    ("I have a lot of growing up to do. I realized that the other day inside my fort.", "Zach Galifianakis"),
    ("I’m not crazy, my reality is just different from yours.", "Cheshire Cat"),
    ("I am big! It's the pictures that got small.", "Norma Desmond"),
    ("The stuff that dreams are made of.", "The Maltese Falcon"),
    ("I love the smell of napalm in the morning.", "Apocalypse Now"),
    ("You can't handle the truth!", "A Few Good Men"),
    ("If you build it, he will come.", "Field of Dreams"),
    ("Keep your friends close, but your enemies closer.", "The Godfather Part II"),
    ("Today, I consider myself the luckiest man on the face of the earth.", "Lou Gehrig"),
    ("A diamond is a chunk of coal that did well under pressure.", "Henry Kissinger"),
    ("Shoot for the moon. Even if you miss, you'll land among the stars.", "Les Brown"),
    ("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    ("You can't cross the sea merely by standing and staring at the water.", "Rabindranath Tagore"),
    ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    ("Everything you’ve ever wanted is on the other side of fear.", "George Addair"),
    ("Hardships often prepare ordinary people for an extraordinary destiny.", "C.S. Lewis"),
    ("Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "Christian D. Larson"),
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("Change your thoughts and you change your world.", "Norman Vincent Peale"),
    ("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
    ("Don't judge each day by the harvest you reap but by the seeds that you plant.", "Robert Louis Stevenson"),
    ("The best preparation for tomorrow is doing your best today.", "H. Jackson Brown, Jr."),
    ("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
    ("I attribute my success to this: I never gave or took any excuse.", "Florence Nightingale"),
    ("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    ("I have failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan"),
    ("The most difficult thing is the decision to act, the rest is merely tenacity.", "Amelia Earhart"),
    ("Definiteness of purpose is the starting point of all achievement.", "W. Clement Stone"),
    ("We become what we think about.", "Earl Nightingale"),
    ("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", "Mark Twain"),
    ("Life is 10% what happens to you and 90% how you react to it.", "Charles R. Swindoll"),
    ("The mind is everything. What you think you become.", "Buddha"),
    ("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
    ("An unexamine life is not worth living.", "Socrates"),
    ("Eighty percent of success is showing up.", "Woody Allen"),
    ("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"),
    ("Winning isn't everything, but wanting to win is.", "Vince Lombardi"),
    ("I am not a product of my circumstances. I am a product of my decisions.", "Stephen Covey"),
    ("Every child is an artist. The problem is how to remain an artist once he grows up.", "Pablo Picasso"),
    ("You can never cross the ocean until you have the courage to lose sight of the shore.", "Christopher Columbus"),
    ("I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "Maya Angelou"),
    ("Either you run the day, or the day runs you.", "Jim Rohn"),
    ("Whether you think you can or you think you can't, you're right.", "Henry Ford"),
    ("The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"),
    ("Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "Johann Wolfgang von Goethe"),
    ("The best revenge is massive success.", "Frank Sinatra"),
    ("People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "Zig Ziglar"),
    ("Life shrinks or expands in proportion to one's courage.", "Anais Nin"),
    ("If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "Vincent Van Gogh"),
    ("There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "Aristotle"),
    ("Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", "Jesus"),
    ("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    ("Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"),
    ("When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "Erma Bombeck"),
    ("Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "Booker T. Washington"),
    ("Certain things catch your eye, but pursue only those that capture the heart.", "Ancient Indian Proverb"),
    ("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    ("Everything you can imagine is real.", "Pablo Picasso"),
    ("When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", "Helen Keller"),
    ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    ("Our lives begin to end the day we become silent about things that matter.", "Martin Luther King Jr."),
    ("Remember that not getting what you want is sometimes a wonderful stroke of luck.", "Dalai Lama"),
    ("The question isn't who is going to let me; it's who is going to stop me.", "Ayn Rand"),
    ("When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", "Henry Ford"),
    ("It's not the years in your life that count. It's the life in your years.", "Abraham Lincoln"),
    ("Change your thoughts and you change your world.", "Norman Vincent Peale"),
    ("Either write something worth reading or do something worth writing.", "Benjamin Franklin"),
    ("Nothing is impossible, the word itself says 'I'm possible'!", "Audrey Hepburn"),
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("If you can dream it, you can achieve it.", "Zig Ziglar"),
    ("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
    ("I am not a product of my circumstances. I am a product of my decisions.", "Stephen Covey"),
    ("When you reach the end of your rope, tie a knot in it and hang on.", "Franklin D. Roosevelt"),
    ("Don't judge each day by the harvest you reap but by the seeds that you plant.", "Robert Louis Stevenson"),
    ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    ("Tell me and I forget. Teach me and I remember. Involve me and I learn.", "Benjamin Franklin"),
    ("The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", "Helen Keller"),
    ("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
    ("Whoever is happy will make others happy too.", "Anne Frank"),
    ("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    ("You will face many defeats in life, but never let yourself be defeated.", "Maya Angelou"),
    ("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"),
    ("Success is walking from failure to failure with no loss of enthusiasm.", "Winston Churchill"),
    ("The only impossible journey is the one you never begin.", "Tony Robbins"),
    ("Only a life lived for others is a life worthwhile.", "Albert Einstein"),
    ("You only live once, but if you do it right, once is enough.", "Mae West"),
    ("Live in the sunshine, swim the sea, drink the wild air.", "Ralph Waldo Emerson"),
    ("Life is really simple, but we insist on making it complicated.", "Confucius"),
    ("May you live all the days of your life.", "Jonathan Swift"),
    ("Life itself is the most wonderful fairy tale.", "Hans Christian Andersen"),
    ("Do not let making a living prevent you from making a life.", "John Wooden"),
    ("Life is ours to be spent, not to be saved.", "D.H. Lawrence"),
    ("Keep smiling, because life is a beautiful thing and there's so much to smile about.", "Marilyn Monroe"),
    ("Life is a long lesson in humility.", "James M. Barrie"),
    ("In the end, it's not the years in your life that count. It's the life in your years.", "Abraham Lincoln"),
    ("Life is made of ever so many partings welded together.", "Charles Dickens"),
    ("Life is trying things to see if they work.", "Ray Bradbury"),
    ("Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas A. Edison"),
    ("If you want to live a happy life, tie it to a goal, not to people or things.", "Albert Einstein"),
    ("Money and success don’t change people; they merely amplify what is already there.", "Will Smith"),
    ("Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"),
    ("Not how long, but how well you have lived is the main thing.", "Seneca"),
    ("I love those who can smile in trouble...", "Leonardo da Vinci"),
    ("Time means a lot to me because, you see, I am also a learner and am often lost in the joy of forever developing and simplifying.", "Bruce Lee"),
    ("The purpose of our lives is to be happy.", "Dalai Lama"),
    ("Life is what happens when you’re busy making other plans.", "John Lennon"),
    ("Get busy living or get busy dying.", "Stephen King"),
    ("You only live once, but if you do it right, once is enough.", "Mae West"),
    ("Many of life’s failures are people who did not realize how close they were to success when they gave up.", "Thomas A. Edison"),
    ("If you want to live a happy life, tie it to a goal, not to people or things.", "Albert Einstein"),
    ("Never let the fear of striking out keep you from playing the game.", "Babe Ruth"),
    ("Money and success don’t change people; they merely amplify what is already there.", "Will Smith"),
    ("Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"),
    ("Not how long, but how well you have lived is the main thing.", "Seneca"),
    ("If life were predictable it would cease to be life, and be without flavor.", "Eleanor Roosevelt"),
    ("The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.", "Henry Ford"),
    ("In order to write about life first you must live it.", "Ernest Hemingway"),
    ("The big lesson in life, baby, is never be scared of anyone or anything.", "Frank Sinatra"),
    ("Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth.", "Mark Twain"),
    ("Curiosity about life in all of its aspects, I think, is still the secret of great creative people.", "Leo Burnett"),
    ("Life is not a problem to be solved, but a reality to be experienced.", "Soren Kierkegaard"),
    ("The unexamined life is not worth living.", "Socrates"),
    ("Turn your wounds into wisdom.", "Oprah Winfrey"),
    ("The way I see it, if you want the rainbow, you gotta put up with the rain.", "Dolly Parton"),
    ("Do all the good you can, for all the people you can, in all the ways you can, as long as you can.", "Hillary Clinton"),
    ("Don’t settle for what life gives you; make life better and build something.", "Ashton Kutcher"),
    ("Everything negative – pressure, challenges – is all an opportunity for me to rise.", "Kobe Bryant"),
    ("I like criticism. It makes you strong.", "LeBron James"),
    ("You never really learn much from hearing yourself speak.", "George Clooney"),
    ("Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this.", "Celine Dion"),
    ("Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.", "John F. Kennedy"),
    ("Live for each second without hesitation.", "Elton John"),
    ("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    ("Life is really simple, but men insist on making it complicated.", "Confucius"),
    ("Life is a succession of lessons which must be lived to be understood.", "Ralph Waldo Emerson"),
    ("My mama always said, life is like a box of chocolates. You never know what you're gonna get.", "Forrest Gump"),
    ("Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits.", "Lao Tzu"),
    ("When we do the best we can, we never know what miracle is wrought in our life, or in the life of another.", "Helen Keller"),
    ("Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "Buddha"),
    ("The brain is wider than the sky.", "Emily Dickinson"),
    ("Great minds discuss ideas; average minds discuss events; small minds discuss people.", "Eleanor Roosevelt"),
    ("Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"),
    ("The best way to predict your future is to create it.", "Abraham Lincoln"),
    ("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    ("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    ("Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"),
    ("If you want to lift yourself up, lift up someone else.", "Booker T. Washington"),
    ("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
    ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas A. Edison"),
    ("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    ("It always seems impossible until it's done.", "Nelson Mandela"),
    ("Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"),
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("Change your thoughts and you change your world.", "Norman Vincent Peale"),
    ("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
    ("If opportunity doesn't knock, build a door.", "Milton Berle"),
    ("You must be the change you wish to see in the world.", "Mahatma Gandhi"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
    ("I am lucky that whatever fear I have inside me, my desire to win is always stronger.", "Serena Williams"),
    ("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
    ("Reading is to the mind what exercise is to the body.", "Joseph Addison"),
    ("The purpose of education is to replace an empty mind with an open one.", "Malcolm Forbes"),
    ("Education is the key to unlock the golden door of freedom.", "George Washington Carver"),
    ("I agree that the loveliest thing to do is to be helpful to others.", "Plato"),
    ("The best way to find yourself is to lose yourself in the service of others.", "Mahatma Gandhi"),
    ("Service to others is the rent you pay for your room here on earth.", "Muhammad Ali"),
    ("We make a living by what we get, but we make a life by what we give.", "Winston Churchill"),
    ("No one has ever become poor by giving.", "Anne Frank"),
    ("Kindness is the language which the deaf can hear and the blind can see.", "Mark Twain"),
    ("A warm smile is the universal language of kindness.", "William Arthur Ward"),
    ("To the world you may be one person, but to one person you may be the world.", "Dr. Seuss")
]

added = 0
print("\\n    // --- Expanded Collection 2 ---")
unique_new = []

for quote, author in candidates:
    # Check length
    if not (50 <= len(quote) <= 150):
        continue
    
    # Check duplicate
    if quote in existing_quotes:
        continue
    
    # Add to existing to prevent duplicates within candidates
    existing_quotes.add(quote)
    unique_new.append(f'    {{ quote: "{quote}", author: "{author}" }},')
    added += 1

# Limit to ~150-200. I had about 200 candidates.
for line in unique_new:
    print(line)

print(f"// Added {added} new quotes.")
